// src/queues/events.ts

export const NotificationTypes = {
  APPROVAL_ALERT: "APPROVAL_ALERT",
  REQUEST_UPDATE: "REQUEST_UPDATE",
  GENERAL_PUSH: "GENERAL_PUSH",
  REQUEST_APPROVED: "REQUEST_APPROVED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  APPROVAL_UPDATE: "APPROVAL_UPDATE"
} as const;
